version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: webapp.dockerfile
    ports:
      - 9527:5000
    depends_on:
      - mysql
      - elasticsearch

  mysql:
    image: "mariadb:10.6.9-focal"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=SakuraAdmin
      - MYSQL_DATABASE=SakuraAdmin
      - MYSQL_PASSWORD=SakuraAdmin
    ports:
      - 13306:3306
    command:
      [ 'mysql','--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci' ]

  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch.dockerfile
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 19200:9200
      - 19300:9300
