version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: webapp.dockerfile
    ports:
      - 9527:5000
    depends_on:
      - mysql
      - elasticsearch

  mysql:
    image: "mariadb:10.6.8-focal"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=Sakura_Admin
      - MYSQL_DATABASE=sakura_admin
      - MYSQL_PASSWORD=Sakura_Admin
    ports:
      - 13306:3306


  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch.dockerfile
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 19200:9200
      - 19300:9300
