# NOTE: Generated By HttpRunner v3.1.11
# FROM: .\testcases\Login.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = (
        Config("登录接口测试")
        .variables(
            **{
                "Opertype": "ADD",
                "poolId": "e3cc3d8b90b4465998ddfec569a66612",
                "resType": "SECURITYGROUP",
                "name": "dyd${random_num()}",
                "secGType": "SECURITY_VM",
                "adapterType": "SINGLE",
                "approvalType": "SECURITYGROUP-ADD",
            }
        )
        .base_url("${ENV(HOST)}")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("登录平台")
            .post("${ENV(HOST)}/auth/login")
            .with_headers(
                **{"accept": "application/json", "Content-Type": "application/json"}
            )
            .with_data({"username": "${ENV(USERNAME)}", "password": "${ENV(PASSWORD)}"})
            .extract()
            .with_jmespath("body.data.token", "access_token")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
