ProjectName:
  - 波塞冬

Env: 测试环境
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
TesterName: 自动化测试

# 域名1
#host: https://www.wanandroid.com
# 域名2，支持多个域名配置
app_host:

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: False

# 报告通知类型：0: 不发送通知  2：企业微信通知 4、飞书通知
NotificationType: 4


# 数据库相关配置
MySqlDB:
  # 数据库开关
  switch: False
  host:
  user: root
  password:
  db: api_test

# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

# 企业通知的相关配置
WeChat:
  webhook:


# 飞书通知
FeiShuTalk:
  webhook: https://open.feishu.cn/open-apis/bot/v2/hook/fce32975-4d2f-49ab-b7a0-72921b173bb9




